### ISSUE TITLE
OPML import should fallback on title when text is not included

### ISSUE THREAD

**Issue by Alkarex** [marienfressinaud/lib_opml#3]
https://github.com/FreshRSS/FreshRSS/issues/1048
https://github.com/FreshRSS/FreshRSS/pull/1112

**Comment by marienfressinaud** [comment]
After (too) many years, I'm going to clean the lib\_opml code and "end" it (there's nothing to add until the spec changes). Considering this issue, it is to the caller to handle the case of a missing `text` attribute, lib\_opml should follow the spec as much as possible. I can do a PR to FRSS if you want.
